name: CI

on:
  pull_request:
    paths:
      - src/tf/**
      - .github/workflows/**
  push:
    branches:
      - main
    paths:
      - src/tf/**
      - .github/workflows/**

permissions:
  contents: read

jobs:
  validate:
    uses: glitchedmob/infra-gha/.github/workflows/tf-validate.yml@v0.7.4
    with:
      init-backend: false
